databaseChangeLog:
  - changeSet:
      id: 42
      author: tlrobinson
      changes:
        - addColumn:
            tableName: report_dashboardcard
            columns:
              - column:
                  name: visualization_settings
                  type: text
                  constraints:
                    nullable: true
                    deferrable: false
                    initiallyDeferred: false
        - addNotNullConstraint:
            columnDataType: text
            columnName: visualization_settings
            defaultNullValue: '{}'
            tableName: report_dashboardcard
